### PR TITLE
Use erlang:timestamp() instead of now() in case of 18 or higer

### PR DESCRIPTION
**Pull request by mururu**

### CODE REVIEW

**Comment by jonmeredith** [comment]
What do you think about including more detailed information on the clock sources used for 18, specifically

```
1> erlang:system_info(os_monotonic_time_source).
[{function,clock_get_time},
 {clock_id,'SYSTEM_CLOCK'},
 {resolution,10000000},
 {extended,no},
 {parallel,yes},
 {time,61318696947449}]
```

and

```
13> erlang:system_info(os_system_time_source).
[{function,clock_get_time},
 {clock_id,'CALENDAR_CLOCK'},
 {resolution,10000000},
 {parallel,yes},
 {time,1435512835094787000}]
```

**Comment by mururu** [comment]
Sounds good!

**Comment by mururu** [comment]
I have added the information. If it is OK, I will update the commit.

before

```
 Current date: {2015,6,29}
 Current time: {12,34,58}
 Current now : {1435,548898,150501}
```

after

```
 Current date     : {2015,6,29}
 Current time     : {12,59,26}
 Current timestamp: {1435,550366,166437}

 erlang:system_info(os_system_time_source):
 [{function,clock_get_time},
  {clock_id,'CALENDAR_CLOCK'},
  {resolution,10000000},
  {parallel,yes},
  {time,1435550366166481000}]

 erlang:system_info(os_monotonic_time_source):
 [{function,clock_get_time},
  {clock_id,'SYSTEM_CLOCK'},
  {resolution,10000000},
  {extended,no},
  {parallel,yes},
  {time,210238155555657}]
```

**Comment by jonmeredith** [comment]
Looks good to me - I'd rather not parse that structure in case things are added to it over time.

Two last things, I'd rather check for the new time API as a capability rather than relying on version strings (Basho build our own versions like "R16B02_basho8") 

```
%% Check for monotonic time support in 18+
try erlang:system_info(os_monotonic_time_source) of
    _ ->
        CONFIG;
catch
    error:badarg ->
        Define = [{d,new_time}],
        case lists:keysearch(erl_opts, 1, CONFIG) of
            {value, {erl_opts, Opts}} ->
                lists:keyreplace(erl_opts, 1, CONFIG, {erl_opts, Opts ++ Define});
            false ->
                CONFIG ++ [{erl_opts, Define}]
        end
end.
```

Also, I wanted to check if you get any errors creating the cluster_info - this is probably a totally unrelated problem.

```
jons-mbp13:ci22 jmeredith$  erl -pa ebin -name 18test -boot start_sasl
Erlang/OTP 18 [erts-7.0] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]
...
Eshell V7.0  (abort with ^G)
(18test@jons-mbp13.jonmeredith.com)1> application:start(cluster_info).
(18test@jons-mbp13.jonmeredith.com)2> cluster_info:dump_local_node("18.dump").
HTML report is at: '18test@jons-mbp13.jonmeredith.com':"18.dump"
Writing report for node '18test@jons-mbp13.jonmeredith.com'

=ERROR REPORT==== 29-Jun-2015::07:39:18 ===
Error in process <0.58.0> on node '18test@jons-mbp13.jonmeredith.com' with exit value:
{terminated,[{io,format,
                 [<0.57.0>,"~n** Registered procs on node ~w **~n",
                  ['18test@jons-mbp13.jonmeredith.com']],
                 []},
             {c,print_node_regs,1,[{file,"c.erl"},{line,639}]},
             {cluster_info,'-capture_io2/3-fun-0-',2,
                           [{file,"src/cluster_info.erl"},{line,289}]}]}

=ERROR REPORT==== 29-Jun-2015::07:39:19 ===
Error in process <0.61.0> on node '18test@jons-mbp13.jonmeredith.com' with exit value:
{terminated,[{io,format,
                 [<0.60.0>," ~s ~s ~s ~s ~s ~s\n",
                  ["id             ","name             ","type ","size  ",
                   "mem     ","owner"]],
                 []},
             {ets,i,0,[{file,"ets.erl"},{line,1562}]},
             {cluster_info,'-capture_io2/3-fun-0-',2,
                           [{file,"src/cluster_info.erl"},{line,289}]}]}

=ERROR REPORT==== 29-Jun-2015::07:39:20 ===
Error in process <0.64.0> on node '18test@jons-mbp13.jonmeredith.com' with exit value:
{terminated,[{io,format,
                 [<0.63.0>,"~-20s ~-7s ~-6s ~8s ~8s ~s~n",
                  ["Node","State","Type","In","Out","Address"]],
                 []},
             {net_kernel,print_info,0,[{file,"net_kernel.erl"},{line,1493}]},
             {cluster_info,'-capture_io2/3-fun-0-',2,
                           [{file,"src/cluster_info.erl"},{line,289}]}]}
[ok]
```

**Comment by mururu** [comment]
I see your points. I updated the commit. But the problem about the error handling is unrelated to this pull request as you said, so I would rather discuss it in another place (issues?).

**Comment by jonmeredith** [comment]
Agreed we should create another issue.  I also was worried about handling mixed clusters with the compile-time detection rather than run-time detection and noticed it had issues with clusters using different versions of erlang _unrelated_ to this patch.

I'm going to be gone on vacation for a week, but will investigate and merge if possible when I get back. If you don't hear from me in ten days or so, please ping me.

**Comment by mururu** [comment]
Sorry for the late reply. Yes, we should detect at run time instead of compile-time. I will change implementaion. And after check clusters using different versions of erlang.

**Comment by slfritchie** [comment]
Just checking ... is there any new activity for this PR that isn't mentioned in the dialog up above?

**Comment by mururu** [comment]
I have pushed the change for run-time detection. I will try to run it with clusters using different versions of erlang for now.

**Comment by mururu** [comment]
It seems to work well with clusters using different versions of erlang.
sample app: https://github.com/mururu/sample_for_cluster_info

**Comment by slfritchie** [comment]
Ito-san, I see another problem with cluster_info, but it appears to be unrelated to your change.  +1, thanks for the patch!

**Comment by mururu** [comment]
Thanks!

**Pull request merged**
